KinderhuisStageOpdracht/Models/Domain/Forum.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices.ComTypes;
using System.Web;

namespace KinderhuisStageOpdracht.Models.Domain
{
    public class Forum
    {
        public int Id { get; set; }
        public virtual Opvoeder Opvoeder { get; set; }
        public virtual Client Client { get; set; }

        public virtual ICollection<Post> Posts { get; set; }

        public Forum()
        {
            Posts = new List<Post>();
        }

        public Forum(Opvoeder opvoeder, Client client)
        {
            Opvoeder = opvoeder;
            Client = client;
            Posts = new List<Post>();
        }

        public void AddPost(string boodschap, Gebruiker gebruiker)
        {
            var post = new Post(boodschap, gebruiker);

            Posts.Add(post);
        }

        public void AddPost(Post post)
        {
            Posts.Add(post);
        }

        public Post GetPost(int id)
        {
            return Posts.FirstOrDefault(p => p.Id == id);
        }

        public void DeletePost(int id)
        {
            var post = Posts.FirstOrDefault(p => p.Id == id);
            Posts.Remove(post);
        }
    }
}

KinderhuisStageOpdracht/Models/Domain/Gebruiker.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.SqlTypes;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using Microsoft.AspNet.Identity;

namespace KinderhuisStageOpdracht.Models.Domain
{
    public abstract class Gebruiker
    {
        public int Id { get; set; }
        public string Voornaam { get; set; }
        public string Naam { get; set; }
        public string Gebruikersnaam { get; set; }
        public string Wachtwoord { get; set; }
        [NotMapped]
        public string PlainWachtwoord { get; set; }
        public string Salt { get; set; }
        public bool Visable { get; set; }

        public virtual ICollection<Taak> Taken { get; set; }
        public virtual Opvangtehuis Opvangtehuis { get; set; }

        [DataType(DataType.ImageUrl)]
        public string ImageUrl { get; set; }

        [DataType(DataType.ImageUrl)]
        public string BackgroundUrl { get; set; }

        /*private string _salt;
        public string Salt
        {
            get
            {
                return _salt;
            }
            set
            {
                _salt = GenerateSalt();
            }
        }*/

        protected Gebruiker()
        {
            Taken = new List<Taak>();
            Visable = true;
            //Salt = GenerateSalt();
        }


        private string GenerateSalt()
        {
            var rng = new RNGCryptoServiceProvider();
            var buffer = new byte[1024];

            rng.GetBytes(buffer);
            var generatedSalt = BitConverter.ToString(buffer);
            /*var stringBuilder = new StringBuilder(Voornaam);
            stringBuilder.Append(Naam);
            stringBuilder.Append(GeboorteDatum.Date.Year);

            var salt = stringBuilder.ToString();*/

            return generatedSalt;
        }

        public string GiveFullName()
        {
            return Voornaam + " " + Naam;
        }

        public string GetOpvangtehuisnaam()
        {
            return Opvangtehuis.Naam;
        }

        public string GetOpvangtehuis()
        {
            return Opvangtehuis.ToString();
        }

        public string GetLeefgroepNaam()
        {
            return Opvangtehuis.Naam;
        }

        public string GetLeefgroepAdres()
        {
            return Opvangtehuis.Straat + " " + Opvangtehuis.StraatNummer;
        }

        public string GetLeefgroepGemeente()
        {
            return Opvangtehuis.Postcode + " " + Opvangtehuis.Gemeente;
        }

        public void EditGebruiker(string naam, string voornaam, Opvangtehuis opvangtehuis,
             string imageUrl)
        {
            Naam = naam;
            Voornaam = voornaam;
            Opvangtehuis = opvangtehuis;

            if (imageUrl != "~/Content/Images/ProfielAfbeelding/dafault.png" || imageUrl != "~/Content/Images/ProfielAfbeelding/dafaultAvatar.png")
            {
                ImageUrl = imageUrl;
            }

        }

        public void DeleteGebruiker()
        {
            Visable = false;
        }

        //Instellingen
        public void AddImage(string imageUrl)
        {
            ImageUrl = imageUrl;
        }


        public void AddBackground(string backgroundUrl)
        {
            BackgroundUrl = backgroundUrl;
        }

        public void WachtwoordAanpassen(string nieuwWachtwoord)
        {
            Wachtwoord = nieuwWachtwoord;
        }
    }
}

KinderhuisStageOpdracht/Models/Domain/KamerControle.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KinderhuisStageOpdracht.Models.Domain
{
    public class KamerControle
    {
        public int Id { get; set; }
        public virtual ICollection<KamerControleItem> KamerControleItems { get; set; }
        public bool AllesInOrde { get; set; }

        public DateTime Datum { get; set; }

        public KamerControle()
        {
            KamerControleItems = new List<KamerControleItem>();
        }

        public KamerControle(DateTime datum)
        {
            Datum = datum;
            KamerControleItems = new List<KamerControleItem>();
            AllesInOrde = IsAllesInOrde();
        }

        public void AddKamerControleItem(KamerControleItem item)
        {
            KamerControleItems.Add(item);
        }

       
        public bool IsAllesInOrde()
        {
            var counter = 0;
            foreach (var i in KamerControleItems)
            {
                if (i.OpdrachtGedaanControle)
                {
                    counter++;
                }
            }
            return KamerControleItems.Count == counter;
        }
       

    }
}

KinderhuisStageOpdracht/Models/Domain/Sanctie.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using Microsoft.SqlServer.Server;

namespace KinderhuisStageOpdracht.Models.Domain
{
    public class Sanctie
    {
        public int Id { get; set; }
        public string Rede { get; set; }

        public DateTime BeginDatum { get; set; }
        public DateTime EindDatum { get; set; }

        public virtual Straf Straf { get; set; }

        public int AantalDagen { get; set; }

        public Sanctie() { }

        public Sanctie(string rede, DateTime datum, DateTime endDate, Straf straf)
        {
            Rede = rede;
            BeginDatum = datum;
            EindDatum = endDate;
            Straf = straf;
        }

        public string GetstrafNaam()
        {
            return Straf.Naam;
        }

        public string GetStrafImageUrl()
        {
            return Straf.ImageUrl;
        }

        public bool GetIfStrafOrBeloning()
        {
            return Straf.StrafOfBeloning;
        }

    }
}

KinderhuisStageOpdracht/Controllers/GebruikerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Configuration;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using KinderhuisStageOpdracht.App_Start;
using KinderhuisStageOpdracht.Extensions;
using KinderhuisStageOpdracht.Models.Domain;
using KinderhuisStageOpdracht.Models.Viewmodels;

namespace KinderhuisStageOpdracht.Controllers
{

    public class GebruikerController : Controller
    {
        private readonly IGebruikerRepository _gebruikerRepository;
        private readonly IOpvangtehuisRepository _opvangtehuisRepository;

        public GebruikerController(IGebruikerRepository gebruikerRepository, IOpvangtehuisRepository opvangtehuisRepository)
        {
            _gebruikerRepository = gebruikerRepository;
            _opvangtehuisRepository = opvangtehuisRepository;
        }

        // GET: Gebruiker
        //[Authorize]
        public ActionResult ClientIndex()
        {
            if (UserStillLoggedIn() || !(_gebruikerRepository.FindById((int)Session["gebruiker"]) is Client))
            {
                return ReturnToLogin();
            }

            if (Session["gebruiker"] == null || !Request.IsAuthenticated)
            {
                return View("Error");
            }

            return View();
        }

        public ActionResult OpvoederOverzicht()
        {
            if (UserStillLoggedIn() || !(_gebruikerRepository.FindById((int)Session["gebruiker"]) is Client))
            {
                return ReturnToLogin();
            }

            var id = (int)Session["gebruiker"];
            var client = (Client)_gebruikerRepository.FindById(id);
            System.Diagnostics.Debug.WriteLine(client.GetType());

            var clientlistvm = new GebruikerViewModel.OpvoederListViewModel();

            List<Gebruiker> opvoeders = _gebruikerRepository.FindAllOpvoeders().Where(c => c.Opvangtehuis.Id == client.Opvangtehuis.Id).ToList();

            foreach (var gebruiker in opvoeders)
            {
                var o = (Opvoeder)gebruiker;
                var opvoedervm = new GebruikerViewModel.OpvoederViewModel(o.Id, o.Voornaam, o.GiveFullName(), o.ImageUrl, false);
                clientlistvm.AddOpvoeder(opvoedervm);
            }

            return View(clientlistvm);
        }

        //[Authorize]
        public ActionResult OpvoederIndex()
        {
            if (UserStillLoggedIn() || !(_gebruikerRepository.FindById((int)Session["gebruiker"]) is Opvoeder))
            {
                return ReturnToLogin();
            }

            if (Session["gebruiker"] == null || !Request.IsAuthenticated)
            {
                return View("Error");
            }
            var id = (int)Session["gebruiker"];
            var opvoeder = (Opvoeder)_gebruikerRepository.FindById(id);
            System.Diagnostics.Debug.WriteLine(opvoeder.GetType());

            var clientlistvm = new GebruikerViewModel.ClientListViewModel();

            List<Gebruiker> clients = _gebruikerRepository.FindAllClients().Where(c => c.Opvangtehuis.Id == opvoeder.Opvangtehuis.Id).ToList();

            foreach (var gebruiker in clients)
            {
                var c = (Client)gebruiker;
                var clientvm = new GebruikerViewModel.ClientViewModel(c.Id, c.GiveFullName(), c.Voornaam, c.ImageUrl, false);

                clientlistvm.AddClient(clientvm);
            }

            return View(clientlistvm);
        }

        //[Authorize]
        public ActionResult AdminIndex(string searchString)
        {
            if (UserStillLoggedIn() || !(_gebruikerRepository.FindById((int)Session["gebruiker"]) is Admin))
            {
                return ReturnToLogin();
            }


            if (Session["gebruiker"] == null || !Request.IsAuthenticated)
            {
                return View("Error");
            }
            var id = (int)Session["gebruiker"];
            //Session["gebruiker"] = id;
            var admin = (Admin)_gebruikerRepository.FindById(id);
            System.Diagnostics.Debug.WriteLine(admin.GetType());

            var opvoederlistvm = new GebruikerViewModel.OpvoederListViewModel();
            var clientlistvm = new GebruikerViewModel.ClientListViewModel();
            var leefgroeplistvm = new GebruikerViewModel.LeefgroepListViewModel();

            List<Gebruiker> opvoeders = _gebruikerRepository.FindAllOpvoeders().ToList();
            List<Gebruiker> clients = _gebruikerRepository.FindAllClients().ToList();

            List<Opvangtehuis> opvangtehuizen = _opvangtehuisRepository.FindAll().ToList();

            if (!String.IsNullOrEmpty(searchString))
            {
                opvoeders = opvoeders.Where(s => s.Naam.ToLower().Contains(searchString.ToLower()) || s.Voornaam.ToLower().Contains(searchString.ToLower())).ToList();
                clients = clients.Where(s => s.Naam.ToLower().Contains(searchString.ToLower()) || s.Voornaam.ToLower().Contains(searchString.ToLower())).ToList();
            }


            foreach (var gebruiker in opvoeders)
            {
                var o = (Opvoeder)gebruiker;
                var opvoedervm = new GebruikerViewModel.OpvoederViewModel(o.Id, o.GiveFullName(),
                    o.GetOpvangtehuisnaam(), o.IsStagair);

                opvoederlistvm.AddOpvoeder(opvoedervm);
            }

            foreach (var gebruiker in clients)
            {
                var c = (Client)gebruiker;
                var clientvm = new GebruikerViewModel.ClientViewModel(c.Id, c.GiveFullName(),
                    c.GetOpvangtehuisnaam());

                clientlistvm.AddClient(clientvm);
            }

            foreach (var opvangtehuis in opvangtehuizen)
            {
                leefgroeplistvm.AddLeefgroep(new GebruikerViewModel.LeefgroepViewModel(opvangtehuis.Id, opvangtehuis.Naam,
                    opvangtehuis.ToString()));
            }



            var oeclvm = new GebruikerViewModel.OpvoederEnClientListViewModel(opvoederlistvm, clientlistvm, leefgroeplistvm);

            return View(oeclvm);
        }

        public ActionResult CreateOpvoeder()
        {
            if (UserStillLoggedIn() || !(_gebruikerRepository.FindById((int)Session["gebruiker"]) is Admin))
            {
                return ReturnToLogin();
            }

            if (!Request.IsAuthenticated)
            {
                return View("Error");
            }

            var covm = new GebruikerViewModel.CreateOpvoederViewModel
            {
                Opvangtehuizen = _opvangtehuisRepository.FindAll().Select(oh => oh.Naam).ToList()
            };
            return View(covm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateOpvoeder(GebruikerViewModel.CreateOpvoederViewModel model)
        {
            if (UserStillLoggedIn() || !(_gebruikerRepository.FindById((int)Session["gebruiker"]) is Admin))
            {
                return ReturnToLogin();
            }

            if (!ImageIsValidType(model.ImageUpload))
            {
                ModelState.AddModelError("ImageUpload", "Dit is geen foto");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (_gebruikerRepository.FindByUsername(model.GebruikersNaam) != null)
                    {
                        this.AddNotification("Er is al reeds iemand met deze gebruikersnaam", NotificationType.ERROR);
                        return RedirectToAction("CreateOpvoeder");
                    }


                    string pass = BCrypt.Net.BCrypt.HashPassword(model.Wachtwoord, BCrypt.Net.BCrypt.GenerateSalt());

                    var opvoeder = new Opvoeder(model.Naam, model.Voornaam,
                        _opvangtehuisRepository.FindByName(model.GeselecteerdOpvangtehuisId), model.GebruikersNaam, pass, ImageUploadProfielAfbeelding(model.ImageUpload), model.IsStagair);

                    //var crypto = new SimpleCrypto.PBKDF2();
                    //var encrytwachtwoord = crypto.Compute(model.Wachtwoord);

                    //var opvoeder = new Opvoeder(model.Naam, model.Voornaam,
                    //    _opvangtehuisRepository.FindByName(model.GeselecteerdOpvangtehuisId), model.GebruikersNaam, encrytwachtwoord, crypto.Salt, ImageUploadProfielAfbeelding(model.ImageUpload), model.IsStagair);

                    _gebruikerRepository.AddOpvoeder(opvoeder);
                    _gebruikerRepository.SaveChanges();

                    this.AddNotification("Opvoeder toegevoegd", NotificationType.SUCCESS);
                    return RedirectToAction("AdminIndex");
                }
                catch (ApplicationException e)
                {
                    ModelState.AddModelError("", e.Message);
                }
            }

            var covm =
                new GebruikerViewModel.CreateOpvoederViewModel(
                    _opvangtehuisRepository.FindAll().Select(oh => oh.Naam).ToList());

            return View(covm);
        }

        public ActionResult CreateClient()
        {
            if (UserStillLoggedIn() || _gebruikerRepository.FindById((int)Session["gebruiker"]) is Client)
            {
                return ReturnToLogin();
            }

            if (!Request.IsAuthenticated)
            {
                return View("Error");
            }

            var ccvm = new GebruikerViewModel.CreateClientViewModel((_gebruikerRepository.FindById((int)Session["gebruiker"])).GetType().Name);

            if (_gebruikerRepository.FindById((int)Session["gebruiker"]) is Admin)
            {
                ccvm.SetOpvangtehuizen(_opvangtehuisRepository.FindAll().Select(oh => oh.Naam).ToList());
            }
            else
            {
                ccvm.AddOpvangtehuis(_gebruikerRepository.FindById((int)Session["gebruiker"]).GetOpvangtehuisnaam());
            }

            return View(ccvm);
        }

KinderhuisStageOpdracht/Views/Gebruiker/CreateClient.cshtml
@model KinderhuisStageOpdracht.Models.Viewmodels.GebruikerViewModel.CreateClientViewModel

@{
    ViewBag.Title = "View";
}

@using (Html.BeginForm("CreateClient", "Gebruiker", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h2>Maak een nieuwe cliënt aan</h2>
    <hr />
    <table class="inputformtable">
        <tr>
            <td>
                @Html.LabelFor(m => m.Voornaam)
            </td>
            <td>
                @Html.TextBoxFor(m => m.Voornaam, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Voornaam, "", new { @class = "text-danger" })
            </td>
        </tr>

        <tr>
            <td>
                @Html.LabelFor(m => m.Naam)
            </td>
            <td>
                @Html.TextBoxFor(m => m.Naam, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Naam, "", new { @class = "text-danger" })
            </td>
        </tr>

        <tr>
            <td>
                @Html.LabelFor(m => m.Opvangtehuizen)
            </td>
            <td>
                @Html.DropDownListFor(m => m.GeselecteerdOpvangtehuisId, new SelectList(Model.Opvangtehuizen), new { @class = "form-control" })
            </td>
        </tr>

        <tr>
            <td>
                @Html.LabelFor(m => m.GebruikersNaam)
            </td>
            <td>
                @Html.TextBoxFor(m => m.GebruikersNaam, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.GebruikersNaam, "", new { @class = "text-danger" })
            </td>
        </tr>

        <tr>
            <td>
                @Html.LabelFor(m => m.Wachtwoord)
            </td>
            <td>
                @Html.PasswordFor(m => m.Wachtwoord, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Wachtwoord, "", new { @class = "text-danger" })
            </td>
        </tr>

        <tr>
            <td>
                @Html.LabelFor(m => m.BevestigWachtwoord)
            </td>
            <td>
                @Html.PasswordFor(m => m.BevestigWachtwoord, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.BevestigWachtwoord, "", new { @class = "text-danger" })
            </td>
        </tr>
    </table>



    <table class="buttontable">
        <tr>
            <td>
                @if (Model.GebruikerType.Contains("Admin"))
                {
                <td>
                    <span class="terugButton">
                        <input type="submit" class="button" value="Voeg cliënt toe" />
                    </span>
                </td>

                    <td>
                        <span class="terugButton">
                            @Html.ActionLink("Terug", "AdminIndex", "Gebruiker")
                        </span>
                    </td>
                }
                else if (Model.GebruikerType.Contains("Opvoeder"))
                {
                    <td>
                        <input type="image" src="@Url.Content("~/Content/Images/Aanduidingen/accept.png")" />
                    </td>
                    <td>
                        <span class="imagebutton">
                            <a href="@Url.Action("OpvoederIndex", "Gebruiker")">
                                <img src="@Url.Content("~/Content/Images/Aanduidingen/terug.png")" alt="Terug" title="Terug" />
                            </a>
                        </span>
                    </td>
                }

            </tr>
        </table>
}

KinderhuisStageOpdracht/Views/Gebruiker/CreateLeefgroep.cshtml
@model KinderhuisStageOpdracht.Models.Viewmodels.GebruikerViewModel.LeefgroepViewModel
@{
    ViewBag.Title = "CreateLeefgroep";
}

@using (Html.BeginForm("CreateLeefgroep", "Gebruiker", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h2>Maak een nieuwe leefgroep aan</h2>
    <hr />

    @*<div class="form-group">
        @Html.LabelFor(m => m.Naam, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Naam, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Naam, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Straat, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Straat, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Straat, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.StraatNummer, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.StraatNummer, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.StraatNummer, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Gemeente, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Gemeente, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Gemeente, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Postcode, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Postcode, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Postcode, "", new { @class = "text-danger" })
        </div>
    </div>*@

    <table class="inputformtable">
        <tr>
            <td>
                @Html.LabelFor(m => m.Naam)
            </td>
            <td>
                @Html.TextBoxFor(m => m.Naam, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Naam, "", new { @class = "text-danger" })
            </td>
        </tr>

        <tr>
            <td>
                @Html.LabelFor(m => m.Straat)
            </td>
            <td>
                @Html.TextBoxFor(m => m.Straat, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Straat, "", new { @class = "text-danger" })
            </td>
        </tr>

        <tr>
            <td>
                @Html.LabelFor(m => m.StraatNummer)
            </td>
            <td>
                @Html.TextBoxFor(m => m.StraatNummer, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.StraatNummer, "", new { @class = "text-danger" })
            </td>
        </tr>

        <tr>
            <td>
                @Html.LabelFor(m => m.Gemeente)
            </td>
            <td>
                @Html.TextBoxFor(m => m.Gemeente, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Gemeente, "", new { @class = "text-danger" })
            </td>
        </tr>

        <tr>
            <td>
                @Html.LabelFor(m => m.Postcode)
            </td>
            <td>
                @Html.TextBoxFor(m => m.Postcode, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Postcode, "", new { @class = "text-danger" })
            </td>
        </tr>
    </table>


    <table class="buttontable">
        <tr>

            <td>
                <span class="terugButton">
                    <input type="submit" class="button" value="Voeg leefgroep toe" />
                </span>
            </td>

            <td>
                <span class="terugButton">
                    @Html.ActionLink("Terug", "AdminIndex", "Gebruiker")
                </span>
            </td>
        </tr>
    </table>
}

KinderhuisStageOpdracht/Views/Gebruiker/CreateSanctie.cshtml
@model KinderhuisStageOpdracht.Models.Viewmodels.GebruikerViewModel.SanctieViewModel
@{
    ViewBag.Title = "CreateSanctie";
}

@using (Html.BeginForm("CreateSanctie", "Gebruiker", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.Id)
    <h2>Maak een beloning/sanctie aan</h2>
    <hr />
    <table class="inputformtable">
        <tr>
            <th>
                @Html.LabelFor(m => m.Client)
            </th>
            <td>
                @Html.DisplayFor(m => m.Client, new { @class = "form-control" })
            </td>
        </tr>

        <tr>
            <th>
                @Html.LabelFor(m => m.Straffen)
            </th>
            <td>
                @Html.DropDownListFor(m => m.GeselecteerdeStraf, new SelectList(Model.Straffen), new { @class = "form-control" })
            </td>
        </tr>

        <tr>
            <th>
                @Html.LabelFor(m => m.Date)
            </th>
            <td>
                @Html.TextBoxFor(m => m.Date, new { @class = "datepickersanctie", @readonly = true, @Value = Model.Date.ToString("dd/MM/yyyy") })

                @Html.ValidationMessageFor(m => m.Date, "", new { @class = "text-danger" })
            </td>
        </tr>

        <tr>
            <th>
                @Html.LabelFor(m => m.EindDatum)
            </th>
            <td>
                @Html.TextBoxFor(m => m.EindDatum, new { @class = "datepickersanctie", @readonly = true, @Value = Model.Date.ToString("dd/MM/yyyy") })

                @Html.ValidationMessageFor(m => m.EindDatum, "", new { @class = "text-danger" })
            </td>
        </tr>

        <tr>
            <th>
                @Html.LabelFor(m => m.Rede)
            </th>
            <td>
                @Html.TextAreaFor(m => m.Rede)
                @Html.ValidationMessageFor(m => m.Rede, "", new { @class = "text-danger" })
            </td>
        </tr>
    </table>

    <table class="buttontable">
        <tr>
            <td>
                <input type="image" src="@Url.Content("~/Content/Images/Aanduidingen/accept.png")" />
            </td>
            <td>
                <span class="imagebutton">
                    <a href="@Url.Action("OpvoederIndex", "Gebruiker")">
                        <img src="@Url.Content("~/Content/Images/Aanduidingen/terug.png")" alt="Terug" title="Terug" />
                    </a>
                </span>
            </td>
        </tr>
    </table>
}

KinderhuisStageOpdracht/Views/Gebruiker/OpvoederOverzicht.cshtml
@model KinderhuisStageOpdracht.Models.Viewmodels.GebruikerViewModel.OpvoederListViewModel
@{
    ViewBag.Title = "OpvoederOverzicht";
}
<h2>Tegen wie wil je iets zeggen?</h2>
<hr />
<div class="imagebutton">
    <a href="@Url.Action("ClientIndex", "Gebruiker")">
        <img src="@Url.Content("~/Content/Images/Aanduidingen/terug.png")" alt="Terug" title="Terug"/>
    </a>
</div>

<div class="opvoederoverviewtable">
    @foreach (var o in Model.Opvoeders)
    {
        <div class="opvoederOverview">
            <div>@Html.Label(o.FullName)</div>  
            <a href="@Url.Action("Forum", new {id = o.Id})">
                <img src="@Url.Content(o.ImageUrl)"/>
            </a>

        </div>
    }

</div>