KinderhuisStageOpdracht/Models/Domain/Klacht.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KinderhuisStageOpdracht.Models.Domain
{
    public class Klacht
    {
        public int Id { get; set; }
        public string Omschrijving { get; set; }
        public DateTime TimeStamp { get; set; }
        public virtual Client Client { get; set; }

        public Klacht(){ }

        public Klacht(string omschrijving, Client client)
        {
            Omschrijving = omschrijving;
            Client = client;
            TimeStamp = DateTime.Now;
        }
    }
}

KinderhuisStageOpdracht/Models/Domain/Opvangtehuis.cs
using System;
using System.Collections.Generic;
using System.Linq;

namespace KinderhuisStageOpdracht.Models.Domain
{
    public class Opvangtehuis
    {
        public int Id { get; set; }
        public string Naam { get; set; }
        public string Straat { get; set; }
        public string StraatNummer { get; set; }
        public string Gemeente { get; set; }
        public string Postcode { get; set; }

        public virtual ICollection<Suggestie> Suggesties { get; set; }
        public virtual ICollection<Menu> Menus { get; set; }

        public virtual ICollection<KamerControleOpdracht> Opdrachten { get; set; }
        public virtual ICollection<Straf> Straffen { get; set; }

        public virtual ICollection<Klacht> Klachten { get; set; }

        public Opvangtehuis()
        {
            Suggesties = new List<Suggestie>();
            Menus = new List<Menu>();
            Klachten = new List<Klacht>();
            Straffen = new List<Straf>();
            Opdrachten = new List<KamerControleOpdracht>();

        }

        public Opvangtehuis(string naam, string straat, string straatnummer, string gemeente, string postcode)
        {
            Naam = naam;
            Straat = straat;
            StraatNummer = straatnummer;
            Gemeente = gemeente;
            Postcode = postcode;
        }


        //Suggesties
        public List<Suggestie> GetSuggesties()
        {
            return Suggesties.OrderByDescending(s => s.TimeStamp).ToList();

        }

        public void AddSuggestie(Suggestie suggestie)
        {
            Suggesties.Add(suggestie);
        }

        public void AddSuggestie(string beschrijving, string genre, Client client)
        {
            var s = new Suggestie()
            {
                Beschrijving = beschrijving,
                Genre = genre,
                Client = client,
                TimeStamp = DateTime.Now
            };
            Suggesties.Add(s);

        }

        public Suggestie FindSuggestieById(int id)
        {
            return Suggesties.FirstOrDefault(s => s.Id == id);
        }

        public void DeleteSuggestie(int id)
        {
            var suggestie = Suggesties.FirstOrDefault(s => s.Id == id);
            Suggesties.Remove(suggestie);
        }


        //Menus
        public List<Menu> GetMenus()
        {
            return Menus.OrderByDescending(m => m.BegindagWeek).ToList();
        }

        public void AddMenu(DateTime begindag)
        {
            var menu = new Menu
            {
                BegindagWeek = begindag
            };
            Menus.Add(menu);
        }

        public Menu FindMenuByDate(DateTime date)
        {
            return Menus.FirstOrDefault(m => m.BegindagWeek == date);
        }

        public void AddMenu(Menu menu)
        {
            Menus.Add(menu);
        }

        public void DeleteMenu(int id)
        {
            var menu = Menus.FirstOrDefault(m => m.Id == id);
            Menus.Remove(menu);
        }

        public Menu GetMenuVanDeWeek()
        {
            var menu = Menus.FirstOrDefault(m => m.BegindagWeek <= DateTime.Today || m.EinddagWeek >= DateTime.Today);
            return menu;
        }

        //Klachten
        public List<Klacht> GetKlachten()
        {
            return Klachten.OrderByDescending(k => k.TimeStamp).ToList();
        }

        public void AddKlacht(Klacht klacht)
        {
            Klachten.Add(klacht);
        }

        public void AddKlacht(string omschrijving, Client client)
        {
            var klacht = new Klacht(omschrijving, client);
            Klachten.Add(klacht);
        }

        public void DeleteKlacht(int id)
        {
            var klacht = Klachten.FirstOrDefault(k => k.Id == id);
            Klachten.Remove(klacht);
        }


        //Straffen
        public void AddStraf(Straf straf)
        {
            Straffen.Add(straf);
        }

        public void AddStraf(string naam, bool strafofbeloning)
        {
            Straffen.Add(new Straf(naam, strafofbeloning));
        }

        public void RemoveStraf(int id)
        {
            var straf = Straffen.FirstOrDefault(s => s.Id == id);
            Straffen.Remove(straf);
        }

        public List<Straf> GetStraffen()
        {
            return Straffen.OrderBy(s => s.Id).ToList();
        }

        public Straf FindStrafByName(string name)
        {
            return Straffen.FirstOrDefault(s => s.Naam == name);
        }


        //Kamercontrole oprachten
        public void AddOpdracht(KamerControleOpdracht opdracht)
        {
            Opdrachten.Add(opdracht);
        }

        public KamerControleOpdracht FindOpdrachById(int id)
        {
            return Opdrachten.FirstOrDefault(o => o.Id == id);
        }

        public void AddOpdrachten(string titel, string imageUrl)
        {
            Opdrachten.Add(new KamerControleOpdracht(titel, imageUrl));
        }

        public List<KamerControleOpdracht> GetKamerControleOpdrachten()
        {
            return Opdrachten.OrderBy(k => k.Titel).ToList();
        }

        public void RemoveOpdracht(int id)
        {
            var opdracht = Opdrachten.FirstOrDefault(o => o.Id == id);
            Opdrachten.Remove(opdracht);
        }

        //Return string
        public override string ToString()
        {
            return String.Format("{0}\n{1} {2}\n{3} {4}", Naam, Straat, StraatNummer, Postcode, Gemeente);
        }

        


    }
}

KinderhuisStageOpdracht/Models/Domain/Suggestie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KinderhuisStageOpdracht.Models.Domain
{
    public class Suggestie
    {
        public int Id { get; set; }
        public string Beschrijving { get; set; }
        public DateTime? TimeStamp { get; set; }
        public virtual Client Client { get; set; }
        public string Genre { get; set; }

        
    }
}

KinderhuisStageOpdracht/Controllers/OpvangtehuisController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Net.Configuration;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.Security;
using KinderhuisStageOpdracht.Extensions;
using KinderhuisStageOpdracht.Models.Domain;
using KinderhuisStageOpdracht.Models.Viewmodels;
using Microsoft.Ajax.Utilities;

namespace KinderhuisStageOpdracht.Controllers
{
    public class OpvangtehuisController : Controller
    {
        private readonly IOpvangtehuisRepository _opvangtehuisRepository;
        private readonly IGebruikerRepository _gebruikerRepository;

        public OpvangtehuisController(IOpvangtehuisRepository opvangtehuisRepository, IGebruikerRepository gebruikerRepository)
        {
            _opvangtehuisRepository = opvangtehuisRepository;
            _gebruikerRepository = gebruikerRepository;
        }

        // GET: Opvangtehuis
        //public ActionResult Suggesties()
        //{
        //    if (UserStillLoggedIn() || !(_gebruikerRepository.FindById((int)Session["gebruiker"]) is Opvoeder))
        //    {
        //        return ReturnToLogin();
        //    }

        //    if (!Request.IsAuthenticated)
        //    {
        //        return View("Error");
        //    }

        //    var opvangtehuis = _gebruikerRepository.FindById((int)Session["gebruiker"]).Opvangtehuis;
        //    var slvm = new OpvangtehuisViewModel.SuggestieListViewModel();

        //    foreach (var s in opvangtehuis.GetSuggesties())
        //    {
        //        var svm = new OpvangtehuisViewModel.SuggestieViewModel(s.TimeStamp, s.Genre, s.Client.GiveFullName(),
        //            s.Beschrijving, s.Id);
        //        slvm.AddSuggestie(svm);
        //    }
        //    return View(slvm);
        //}

        public ActionResult Suggesties(string sortingOrder)
        {
            if (UserStillLoggedIn() || !(_gebruikerRepository.FindById((int)Session["gebruiker"]) is Opvoeder))
            {
                return ReturnToLogin();
            }

            var opvangtehuis = _gebruikerRepository.FindById((int)Session["gebruiker"]).Opvangtehuis;
            var slvm = new OpvangtehuisViewModel.SuggestieListViewModel();

            foreach (var s in opvangtehuis.GetSuggesties())
            {
                var svm = new OpvangtehuisViewModel.SuggestieViewModel(s.TimeStamp, s.Genre, s.Client.GiveFullName(),
                    s.Beschrijving, s.Id);
                slvm.AddSuggestie(svm);
            }

            switch (sortingOrder)
            {
                case "Genre":
                    slvm.Suggesties = slvm.Suggesties.OrderBy(m => m.Genre).ToList();
                    break;
                case "Client":
                    slvm.Suggesties = slvm.Suggesties.OrderBy(m => m.Client).ToList(); ;
                    break;
                case "Wanneer":
                    slvm.Suggesties = slvm.Suggesties.OrderByDescending(m => m.TimeStamp).ToList(); ;
                    break;
            }

            return View(slvm);
        }


        public ActionResult CreateSuggestie()
        {
            if (UserStillLoggedIn() || !(_gebruikerRepository.FindById((int)Session["gebruiker"]) is Client))
            {
                return ReturnToLogin();
            }

            if (!Request.IsAuthenticated)
            {
                return View("Error");
            }

            var csvm = new OpvangtehuisViewModel.CreateSuggestieViewModel();
            return View(csvm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateSuggestie(OpvangtehuisViewModel.CreateSuggestieViewModel model)
        {
            if (UserStillLoggedIn() || !(_gebruikerRepository.FindById((int)Session["gebruiker"]) is Client))
            {
                return ReturnToLogin();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var opvangtehuis = _gebruikerRepository.FindById((int)Session["gebruiker"]).Opvangtehuis;
                    opvangtehuis.AddSuggestie(model.Beschrijving, model.GeselecteerdGenre,
                        (Client)_gebruikerRepository.FindById((int)Session["gebruiker"]));
                    _opvangtehuisRepository.SaveChanges();

                    this.AddNotification("Je suggestie wordt doorgegeven", NotificationType.SUCCESS);
                    return RedirectToAction("ClientIndex", "Gebruiker");
                }
                catch (ApplicationException e)
                {
                    ModelState.AddModelError("", e.Message);
                }
                catch (Exception e)
                {
                    ModelState.AddModelError("", e.Message);
                    return View("Error");
                }
            }

            var csvm = new OpvangtehuisViewModel.CreateSuggestieViewModel();
            return View(csvm);

        }

        //public ActionResult DeleteSuggestie(int id)
        //{
        //    if (UserStillLoggedIn() != null)
        //    {
        //        return UserStillLoggedIn();
        //    }

        //    if (!Request.IsAuthenticated)
        //    {
        //        return View("Error");
        //    }

        //    var s = _gebruikerRepository.FindById((int)Session["gebruiker"]).Opvangtehuis.FindSuggestieById(id);
        //    var svm = new OpvangtehuisViewModel.SuggestieViewModel(s.TimeStamp, s.Genre, s.Client.GiveFullName(), s.Beschrijving, s.Id);

        //    return View(svm);
        //}

        //[HttpPost, ActionName("DeleteSuggestie")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteSuggestion(int id)
        //{
        //    if (UserStillLoggedIn() != null)
        //    {
        //        return UserStillLoggedIn();
        //    }
        //    try
        //    {
        //        var opvangtehuis = _gebruikerRepository.FindById((int)Session["gebruiker"]).Opvangtehuis;
        //        opvangtehuis.DeleteSuggestie(id);
        //        _opvangtehuisRepository.SaveChanges();

        //        this.AddNotification("De suggestie is verwijderd", NotificationType.SUCCESS);
        //        return RedirectToAction("Suggesties");
        //    }
        //    catch (ApplicationException e)
        //    {
        //        ModelState.AddModelError("", e.Message);
        //    }
        //    return View();
        //}

        [HttpPost]
        public ActionResult DeleteSuggestion(int id)
        {
            if (UserStillLoggedIn() || !(_gebruikerRepository.FindById((int)Session["gebruiker"]) is Opvoeder))
            {
                return ReturnToLogin();
            }
            try
            {
                var opvangtehuis = _gebruikerRepository.FindById((int)Session["gebruiker"]).Opvangtehuis;
                opvangtehuis.DeleteSuggestie(id);
                _opvangtehuisRepository.SaveChanges();

                return RedirectToAction("Suggesties");

            }
            catch (ApplicationException e)
            {
                ModelState.AddModelError("", e.Message);
            }
            catch (NullReferenceException e)
            {
                ModelState.AddModelError("", e.Message);
                return RedirectToAction("OpvoederIndex", "Gebruiker");
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", e.Message);
                return View("Error");
            }
            return RedirectToAction("Suggesties");
        }

        public ActionResult MenuIndex()
        {
            if (UserStillLoggedIn() || !(_gebruikerRepository.FindById((int)Session["gebruiker"]) is Opvoeder))
            {
                return ReturnToLogin();
            }

            if (!Request.IsAuthenticated)
            {
                return View("Error");
            }

            var opvangtehuis = _gebruikerRepository.FindById((int)Session["gebruiker"]).Opvangtehuis;
            var mlvm = new OpvangtehuisViewModel.MenuListViewModel();

            foreach (var m in opvangtehuis.GetMenus())
            {
                var mvm = new OpvangtehuisViewModel.MenuViewModel(m.Id, m.Week, m.BegindagWeek, m.EinddagWeek);

                mlvm.AddMenu(mvm);
            }

            return View(mlvm);
        }

        [HttpPost]
        public ActionResult DeleteMenu(int id)
        {
            if (UserStillLoggedIn() || !(_gebruikerRepository.FindById((int)Session["gebruiker"]) is Opvoeder))
            {
                return ReturnToLogin();
            }
            try
            {
                var opvangtehuis = _gebruikerRepository.FindById((int)Session["gebruiker"]).Opvangtehuis;
                opvangtehuis.DeleteMenu(id);
                _opvangtehuisRepository.SaveChanges();

                return RedirectToAction("Suggesties");

            }
            catch (ApplicationException e)
            {
                ModelState.AddModelError("", e.Message);
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", e.Message);
                return View("Error");
            }

            return RedirectToAction("Suggesties");
        }

        public ActionResult CreateMenu()
        {
            if (UserStillLoggedIn())
            {
                return ReturnToLogin();
            }

            if (!Request.IsAuthenticated)
            {
                return View("Error");
            }

            var mvm = new OpvangtehuisViewModel.MenuViewModel();
            return View(mvm);
        }

        //[HttpPost]
        //public ActionResult CreateMenu(OpvangtehuisViewModel.MenuViewModel model)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        var menu = new Menu
        //        {
        //            BegindagWeek = model.BeginWeek,

KinderhuisStageOpdracht/Views/Opvangtehuis/CreateMenu.cshtml
@model KinderhuisStageOpdracht.Models.Viewmodels.OpvangtehuisViewModel.MenuViewModel

@{
    ViewBag.Title = "CreateMenu";
}

@using (Html.BeginForm("CreateMenu", "Opvangtehuis", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.Id)
    <div id="menuDate">
      
        <div>
            @if (Model.Id <= 0)
            {
                <h2 style="text-align: left">Menu aanmaken</h2>
                <hr/>
                @Html.LabelFor(m => m.BeginWeek, new { @class = "control-label" })
                @Html.TextBoxFor(m => m.BeginWeek, new { @class = "datepickermonday", @readonly = true, @Value = Model.BeginWeek.ToString("dd/MM/yyyy") })
                @Html.ValidationMessageFor(m => m.BeginWeek, "", new { @class = "text-danger" })
            }
            else
            {
                <h2 style="text-align: left">Menu aanpassen</h2>
                <hr />
                @Html.LabelFor(m => m.BeginWeek, new { @class = "control-label" })
                @Html.TextBoxFor(m => m.BeginWeek, new { @class = "datepickermondayedit", @readonly = true, @Value = Model.BeginWeek.ToString("dd/MM/yyyy") })
                @Html.ValidationMessageFor(m => m.BeginWeek, "", new { @class = "text-danger" })
            }
            <h2 style="color: red">Altijd eerst er voor zorgen dat de geslecteerde datum zeker een maandag is, anders moet je alles opnieuw typen.</h2>

        </div>
    </div>

    <table class="formPage form menutable">
        <tr>
            <th></th>
            <th>Vul gerecht 1 in</th>
            <th>Vul gerecht 2 in</th>
            <th>Vul gerecht 3 in</th>
        </tr>
        
        <tr>
            <th>Maandag</th>
            <td>
                @Html.TextBoxFor(m => m.MaandagViewModel.Voorgerecht, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.MaandagViewModel.Dessert, "", new { @class = "text-danger" })
            </td>
            <td>
                @Html.TextBoxFor(m => m.MaandagViewModel.Hoofdgerecht, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.MaandagViewModel.Dessert, "", new { @class = "text-danger" })
            </td>
            <td>
                @Html.TextBoxFor(m => m.MaandagViewModel.Dessert, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.MaandagViewModel.Dessert, "", new { @class = "text-danger" })
            </td>
        </tr>

        <tr>
            <th>Dinsdag</th>
            <td>
                @Html.TextBoxFor(m => m.DinsdagViewModel.Voorgerecht, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.DinsdagViewModel.Dessert, "", new { @class = "text-danger" })
            </td>
            <td>
                @Html.TextBoxFor(m => m.DinsdagViewModel.Hoofdgerecht, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.DinsdagViewModel.Dessert, "", new { @class = "text-danger" })
            </td>
            <td>
                @Html.TextBoxFor(m => m.DinsdagViewModel.Dessert, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.DinsdagViewModel.Dessert, "", new { @class = "text-danger" })
            </td>
        </tr>

        <tr>
            <th>Woensdag</th>
            <td>
                @Html.TextBoxFor(m => m.WoensdagViewModel.Voorgerecht, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.WoensdagViewModel.Dessert, "", new { @class = "text-danger" })
            </td>
            <td>
                @Html.TextBoxFor(m => m.WoensdagViewModel.Hoofdgerecht, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.WoensdagViewModel.Dessert, "", new { @class = "text-danger" })
            </td>
            <td>
                @Html.TextBoxFor(m => m.WoensdagViewModel.Dessert, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.WoensdagViewModel.Dessert, "", new { @class = "text-danger" })
            </td>
        </tr>

        <tr>
            <th>Donderdag</th>
            <td>
                @Html.TextBoxFor(m => m.DonderdagViewModel.Voorgerecht, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.DonderdagViewModel.Dessert, "", new { @class = "text-danger" })
            </td>
            <td>
                @Html.TextBoxFor(m => m.DonderdagViewModel.Hoofdgerecht, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.DonderdagViewModel.Dessert, "", new { @class = "text-danger" })
            </td>
            <td>
                @Html.TextBoxFor(m => m.DonderdagViewModel.Dessert, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.DonderdagViewModel.Dessert, "", new { @class = "text-danger" })
            </td>
        </tr>

        <tr>
            <th>Vrijdag</th>
            <td>
                @Html.TextBoxFor(m => m.VrijdagViewModel.Voorgerecht, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.VrijdagViewModel.Dessert, "", new { @class = "text-danger" })
            </td>
            <td>
                @Html.TextBoxFor(m => m.VrijdagViewModel.Hoofdgerecht, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.VrijdagViewModel.Dessert, "", new { @class = "text-danger" })
            </td>
            <td>
                @Html.TextBoxFor(m => m.VrijdagViewModel.Dessert, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.VrijdagViewModel.Dessert, "", new { @class = "text-danger" })
            </td>
        </tr>

        <tr>
            <th>Zaterdag</th>
            <td>
                @Html.TextBoxFor(m => m.ZaterdagViewModel.Voorgerecht, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.ZaterdagViewModel.Dessert, "", new { @class = "text-danger" })
            </td>
            <td>
                @Html.TextBoxFor(m => m.ZaterdagViewModel.Hoofdgerecht, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.ZaterdagViewModel.Dessert, "", new { @class = "text-danger" })
            </td>
            <td>
                @Html.TextBoxFor(m => m.ZaterdagViewModel.Dessert, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.ZaterdagViewModel.Dessert, "", new { @class = "text-danger" })
            </td>
        </tr>

        <tr>
            <th>Zondag</th>
            <td>
                @Html.TextBoxFor(m => m.ZondagViewModel.Voorgerecht, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.ZondagViewModel.Dessert, "", new { @class = "text-danger" })
            </td>
            <td>
                @Html.TextBoxFor(m => m.ZondagViewModel.Hoofdgerecht, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.ZondagViewModel.Dessert, "", new { @class = "text-danger" })
            </td>
            <td>
                @Html.TextBoxFor(m => m.ZondagViewModel.Dessert, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.ZondagViewModel.Dessert, "", new { @class = "text-danger" })
            </td>
        </tr>
    </table>



    <table class="buttontable">
        <tr>
            <td>
                <input type="image" src="@Url.Content("~/Content/Images/Aanduidingen/accept.png")" />
            </td>
            <td>
                <span class="imagebutton">
                    <a href="@Url.Action("MenuIndex")">
                        <img src="@Url.Content("~/Content/Images/Aanduidingen/terug.png")" alt="Terug" title="Terug" />
                    </a>
                </span>
            </td>
        </tr>
    </table>
}

KinderhuisStageOpdracht/Views/Opvangtehuis/CreateSuggestie.cshtml
@model KinderhuisStageOpdracht.Models.Viewmodels.OpvangtehuisViewModel.CreateSuggestieViewModel
@{
    ViewBag.Title = "Geef ons een suggestie";
}


@using (Html.BeginForm("CreateSuggestie", "Opvangtehuis", FormMethod.Post, new { @class = "", role = "form" }))
{
    <h2>@ViewBag.Title</h2>
    <hr/>
    @Html.AntiForgeryToken()
    <table class="suggestieform">
        <tr>
            <td>
                <label>
                    @Html.RadioButtonFor(m => m.GeselecteerdGenre, "Eten", new { @checked = true })
                    <img src="@Url.Content("~/Content/Images/Aanduidingen/eten.png")" alt="Een suggestie over het eten doen" title="Een suggestie over het eten doen" class="suggestionImage" />
                </label>
            </td>
            <td>
                <label>
                    @Html.RadioButtonFor(m => m.GeselecteerdGenre, "Activitiet")
                    <img src="@Url.Content("~/Content/Images/Aanduidingen/activiteit.png")" alt="Een suggestie over een activiteit doen" title="Een suggestie over een activiteit doen" class="suggestionImage" />
                </label>
            </td>
            <td>
                <label>
                    @Html.RadioButtonFor(m => m.GeselecteerdGenre, "Film")
                    <img src="@Url.Content("~/Content/Images/Aanduidingen/film.png")" alt="Een suggestie over een film doen" title="Een suggestie over een film doen" class="suggestionImage" />
                </label>
            </td>
            <td>
                <label>
                    @Html.RadioButtonFor(m => m.GeselecteerdGenre, "Algemeen")
                    <img src="@Url.Content("~/Content/Images/Aanduidingen/algemeen.png")" alt="Een algemene suggestie doen" title="Een algemene suggestie doen" class="suggestionImage" />
                </label>
            </td>


        </tr>
        <tr>
            <td colspan="4">
                @Html.LabelFor(m => m.Beschrijving, new { @class = "control-label" })<br />
                @Html.TextAreaFor(m => m.Beschrijving, new { @class = "form-control", @cols = 40, @rows = 5 })
                @Html.ValidationMessageFor(m => m.Beschrijving, "", new { @class = "text-danger" })
            </td>
        </tr>


    </table>
    <br />
    <table class="buttontable">
        <tr>
            <td>
                <div class="imagebutton">
                    <input type="image" src="@Url.Content("~/Content/Images/Aanduidingen/accept.png")" alt="Accepteren" title="Accpeteren" />
                </div>
            </td>
            <td>
                <div class="imagebutton">
                    <a href="@Url.Action("ClientIndex", "Gebruiker")">
                        <img src="@Url.Content("~/Content/Images/Aanduidingen/terug.png")" alt="Terug" title="Terug" />
                    </a>
                </div>
            </td>
        </tr>
    </table>
}

KinderhuisStageOpdracht/Views/Opvangtehuis/Klacht.cshtml
@model KinderhuisStageOpdracht.Models.Viewmodels.OpvangtehuisViewModel.KlachtViewModel
@{
    ViewBag.Title = "Klacht";
}

<h2>Heb je een klacht voor ons?</h2>
<hr/>
@using (Html.BeginForm("Klacht", "Opvangtehuis", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <table class="form">
        <tr>
            <th>
                @Html.LabelFor(m => m.Omschrijving, new { @class = "control-label" })
            </th>
        </tr>
        <tr>
            <td>
                @Html.TextAreaFor(m => m.Omschrijving, new { @class = "form-control", @cols = 30, @rows = 5 })
                @Html.ValidationMessageFor(m => m.Omschrijving, "", new { @class = "text-danger" })
            </td>
        </tr>
    </table>

    <table class="buttontable">
        <tr>
            <td>
                <input type="image" src="@Url.Content("~/Content/Images/Aanduidingen/accept.png")" />
            </td>
            <td>
                <span class="imagebutton">
                    <a href="@Url.Action("ClientIndex", "Gebruiker")">
                        <img src="@Url.Content("~/Content/Images/Aanduidingen/terug.png")" alt="Terug" title="Terug" />
                    </a>
                </span>
            </td>
        </tr>
    </table>
}